name: xBan
main: de.mark615.xban.XBan
version: 1.0
description: Ban and Mute Plugin
author: [Mark615 Happykobolt4]

commands:
  ban:
    description: ban command
    usage: /ban
    aliases: [xban, xb]
    default: op
  unban:
    description: unban command
    usage: /unban
    aliases: [xunban, xub]
    default: op
  mute:
    description: mute command
    usage: /mute
    aliases: [xmute, xm]
    default: op
  unmute:
    description: unmute command
    usage: /unmute
    aliases: [xunmute, xum]
    default: op